import {
  AlertTriangle,
  BookOpen,
  Boxes,
  BrainCircuit,
  ClipboardList,
  Database,
  FileCheck2,
  GitBranch,
  FlaskConical,
  Gauge,
  Home,
  Presentation,
  RadioTower,
  Radar,
  RefreshCw,
  Rocket,
  Settings,
  ShieldCheck,
  Workflow
} from "lucide-react";

export const navigationItems = [
  { label: "Dashboard", path: "/", icon: Home },
  { label: "Portfolio", path: "/portfolio", icon: Presentation },
  { label: "Projects", path: "/projects", icon: Boxes },
  { label: "Examples", path: "/examples", icon: BookOpen },
  { label: "Datasets", path: "/datasets", icon: Database },
  { label: "Feature Store", path: "/feature-store", icon: GitBranch },
  { label: "Experiments", path: "/experiments", icon: FlaskConical },
  { label: "Training Runs", path: "/training-runs", icon: Workflow },
  { label: "Models", path: "/models", icon: BrainCircuit },
  { label: "Deployments", path: "/deployments", icon: Rocket },
  { label: "Inference", path: "/inference", icon: RadioTower },
  { label: "Monitoring", path: "/monitoring", icon: Gauge },
  { label: "Drift", path: "/drift", icon: Radar },
  { label: "Retraining", path: "/retraining", icon: RefreshCw },
  { label: "Alerts", path: "/alerts", icon: AlertTriangle },
  { label: "Release Evidence", path: "/release-evidence", icon: FileCheck2 },
  { label: "Operational Audit", path: "/operational-audit", icon: ClipboardList },
  { label: "Admin", path: "/admin", icon: ShieldCheck },
  { label: "Settings", path: "/settings", icon: Settings }
] as const;
