from __future__ import annotations

import argparse
import json
import shutil
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

DEMO_RESET_SCHEMA_VERSION = "forgeml.demo_reset.v1"
DEFAULT_STATE_DIR = Path(".forgeml/demo")
DEFAULT_RELEASE_MANIFEST_OUTPUT = Path("dist/release/forgeml-release-manifest.json")
DEFAULT_SCREENSHOT_DIR = Path("test-results")
DEFAULT_OUTPUT_PATH = Path(".forgeml/demo/demo-reset-report.json")


class DemoResetError(RuntimeError):
    pass


@dataclass(frozen=True)
class DemoResetTarget:
    code: str
    description: str
    path: Path
    kind: str


def safe_reset_targets(
    *,
    state_dir: Path = DEFAULT_STATE_DIR,
    release_manifest_output: Path = DEFAULT_RELEASE_MANIFEST_OUTPUT,
    screenshot_dir: Path = DEFAULT_SCREENSHOT_DIR,
    include_screenshots: bool = True,
) -> tuple[DemoResetTarget, ...]:
    targets = [
        DemoResetTarget(
            code="demo_state",
            description="Local demo summaries, refresh reports, and generated artifacts.",
            path=state_dir,
            kind="directory",
        ),
        DemoResetTarget(
            code="release_manifest",
            description="Local release manifest regenerated by the fresh demo stack.",
            path=release_manifest_output,
            kind="file",
        ),
    ]
    if include_screenshots:
        targets.append(
            DemoResetTarget(
                code="demo_screenshots",
                description="Deterministic Playwright screenshot output.",
                path=screenshot_dir,
                kind="directory",
            )
        )
    return tuple(targets)


def build_demo_reset_plan(
    *,
    repo_root: Path,
    state_dir: Path = DEFAULT_STATE_DIR,
    release_manifest_output: Path = DEFAULT_RELEASE_MANIFEST_OUTPUT,
    screenshot_dir: Path = DEFAULT_SCREENSHOT_DIR,
    include_screenshots: bool = True,
) -> dict[str, Any]:
    targets = safe_reset_targets(
        state_dir=state_dir,
        release_manifest_output=release_manifest_output,
        screenshot_dir=screenshot_dir,
        include_screenshots=include_screenshots,
    )
    return {
        "schema_version": DEMO_RESET_SCHEMA_VERSION,
        "repo_root": repo_root.resolve().as_posix(),
        "safety_policy": {
            "mode": "repo_scoped_filesystem_cleanup",
            "docker_volumes_removed": False,
            "database_rows_removed": False,
        },
        "targets": [
            {
                **asdict(target),
                "path": target.path.as_posix(),
                "exists": _resolve_target_path(repo_root, target).exists(),
            }
            for target in targets
        ],
        "reviewer_next_commands": [
            "make demo-stack-fresh",
            "make demo-walkthrough",
            "make demo-screenshots",
        ],
    }


def reset_demo_environment(
    *,
    repo_root: Path,
    targets: tuple[DemoResetTarget, ...],
    dry_run: bool,
) -> dict[str, Any]:
    removed: list[dict[str, str]] = []
    skipped: list[dict[str, str]] = []
    for target in targets:
        target_path = _resolve_target_path(repo_root, target)
        if not target_path.exists():
            skipped.append(
                {
                    "code": target.code,
                    "path": target.path.as_posix(),
                    "reason": "not_present",
                }
            )
            continue
        if dry_run:
            skipped.append(
                {
                    "code": target.code,
                    "path": target.path.as_posix(),
                    "reason": "dry_run",
                }
            )
            continue
        _remove_target(target_path, target)
        removed.append({"code": target.code, "path": target.path.as_posix()})

    return {
        "schema_version": DEMO_RESET_SCHEMA_VERSION,
        "dry_run": dry_run,
        "removed": removed,
        "skipped": skipped,
        "target_count": len(targets),
        "reviewer_next_commands": [
            "make demo-stack-fresh",
            "make demo-walkthrough",
            "make demo-screenshots",
        ],
    }


def serialize_demo_reset_report(report: dict[str, Any]) -> str:
    return json.dumps(report, indent=2, sort_keys=True) + "\n"


def write_demo_reset_report(report: dict[str, Any], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(serialize_demo_reset_report(report), encoding="utf-8")


def _resolve_target_path(repo_root: Path, target: DemoResetTarget) -> Path:
    root = repo_root.resolve()
    candidate = target.path if target.path.is_absolute() else root / target.path
    resolved = candidate.resolve()
    try:
        resolved.relative_to(root)
    except ValueError as exc:
        raise DemoResetError(
            f"Demo reset target must be inside the repository: {target.path}"
        ) from exc
    if resolved == root:
        raise DemoResetError("Demo reset target cannot be the repository root.")
    return resolved


def _remove_target(target_path: Path, target: DemoResetTarget) -> None:
    if target.kind == "directory":
        if not target_path.is_dir():
            raise DemoResetError(f"Demo reset target is not a directory: {target.path}")
        shutil.rmtree(target_path)
        return
    if target.kind == "file":
        if not target_path.is_file():
            raise DemoResetError(f"Demo reset target is not a file: {target.path}")
        target_path.unlink()
        return
    raise DemoResetError(f"Unsupported demo reset target kind: {target.kind}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Reset ForgeML local demo outputs before a fresh reviewer run."
    )
    parser.add_argument("--repo-root", type=Path, default=Path("."))
    parser.add_argument("--state-dir", type=Path, default=DEFAULT_STATE_DIR)
    parser.add_argument(
        "--release-manifest-output",
        type=Path,
        default=DEFAULT_RELEASE_MANIFEST_OUTPUT,
    )
    parser.add_argument("--screenshot-dir", type=Path, default=DEFAULT_SCREENSHOT_DIR)
    parser.add_argument("--keep-screenshots", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--plan", action="store_true")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT_PATH)
    args = parser.parse_args(argv)

    repo_root = args.repo_root.resolve()
    try:
        if args.plan:
            report = build_demo_reset_plan(
                repo_root=repo_root,
                state_dir=args.state_dir,
                release_manifest_output=args.release_manifest_output,
                screenshot_dir=args.screenshot_dir,
                include_screenshots=not args.keep_screenshots,
            )
        else:
            report = reset_demo_environment(
                repo_root=repo_root,
                targets=safe_reset_targets(
                    state_dir=args.state_dir,
                    release_manifest_output=args.release_manifest_output,
                    screenshot_dir=args.screenshot_dir,
                    include_screenshots=not args.keep_screenshots,
                ),
                dry_run=args.dry_run,
            )
    except DemoResetError as exc:
        print(f"FAIL {exc}", file=sys.stderr)
        return 1

    write_demo_reset_report(report, args.output)
    print(serialize_demo_reset_report(report), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
